// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9P5Nlac6pYMMvJClcAldaPNjgOyuBBV4',
    appId: '1:249655633617:web:2804764064bbe86f3947f0',
    messagingSenderId: '249655633617',
    projectId: 'geminigeeks-86f4c',
    authDomain: 'geminigeeks-86f4c.firebaseapp.com',
    storageBucket: 'geminigeeks-86f4c.appspot.com',
    measurementId: 'G-FQF4JK0T1W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBDhxkZ7d0CqXBKLK5_2PzwJv2C8iZ_HA',
    appId: '1:249655633617:android:61b549394a0924333947f0',
    messagingSenderId: '249655633617',
    projectId: 'geminigeeks-86f4c',
    storageBucket: 'geminigeeks-86f4c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbYZVWVTvCfzmABigtMq8IQtiOkydK820',
    appId: '1:249655633617:ios:31f3d9b2987338293947f0',
    messagingSenderId: '249655633617',
    projectId: 'geminigeeks-86f4c',
    storageBucket: 'geminigeeks-86f4c.appspot.com',
    iosBundleId: 'com.example.chatWithVideo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbYZVWVTvCfzmABigtMq8IQtiOkydK820',
    appId: '1:249655633617:ios:31f3d9b2987338293947f0',
    messagingSenderId: '249655633617',
    projectId: 'geminigeeks-86f4c',
    storageBucket: 'geminigeeks-86f4c.appspot.com',
    iosBundleId: 'com.example.chatWithVideo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9P5Nlac6pYMMvJClcAldaPNjgOyuBBV4',
    appId: '1:249655633617:web:c4c03b3ae6a89f4f3947f0',
    messagingSenderId: '249655633617',
    projectId: 'geminigeeks-86f4c',
    authDomain: 'geminigeeks-86f4c.firebaseapp.com',
    storageBucket: 'geminigeeks-86f4c.appspot.com',
    measurementId: 'G-BLPMFZXVJM',
  );
}
